/**
 * NoirNote — Türkçe metin kaynağı (tek kaynak).
 *
 * Kurallar:
 * - Kullanıcıya görünen tüm metinler buradan gelmeli.
 * - Bileşenler/sayfalar içinde metin sabitlemeyin.
 * - Gelecekte `texts.en.ts` eklemek için anahtar yapısını semantik tutun.
 */
export const textsTR = {
  common: {
    appName: "NoirNote",
    loading: "Yükleniyor…",
    continue: "Devam et",
    back: "Geri",
    close: "Kapat",
    cancel: "İptal",
    questionMark: "?",
    cross: "✗",
    checkmark: "✅",
    about: "Hakkında",
  },
  meta: {
    title: "NoirNote",
    description:
      "NoirNote: cinayet çıkarımı ve mantık bulmacası oyunu. (Kurulum aşaması)",
  },
  home: {
    title: "NoirNote",
    subtitle:
      "Cinayet çıkarımı ve mantık bulmacaları için minimal temel kurulum.",
    description: "NoirNote, mantık yürütme ile cinayet gizemini birleştiren dedüksiyon temelli bir bulmaca oyunudur.\nHer vakada Kim? Nerede? Neyle? sorularının tek doğru cevabını, ipuçlarını eleyerek ve dedektif not defterini doğru kullanarak bulman gerekir.\nUnutma dedektif, suçu kanıtlanana kadar herkes masumdur...",
    descriptionEn: "NoirNote is a deduction-based puzzle game that blends logic with murder mystery.\nIn every case, you must uncover the single correct answer to Who? Where? With what? by eliminating clues and using your detective notebook wisely.\nRemember, detective—everyone is innocent until proven guilty.",
    mainSlogan: "Kanıt yoksa suç da yoktur.",
    mainSloganEn: "Mark it. Prove it.",
    primaryCta: "Giriş yap",
    secondaryCta: "Vaka paneline git",
    primaryCtaEn: "Sign In",
    secondaryCtaEn: "Go to Dashboard",
  },
  login: {
    title: "Giriş",
    subtitle: "Devam etmek için hesabınla giriş yap.",
    emailLabel: "E-posta",
    passwordLabel: "Şifre",
    emailPlaceholder: "ornek@email.com",
    passwordPlaceholder: "Şifrenizi girin",
    signInButton: "Giriş Yap",
    signUpButton: "Kayıt Ol",
    googleButton: "Google ile giriş yap",
    signingIn: "Giriş yapılıyor…",
    signingUp: "Kayıt oluşturuluyor…",
    redirecting: "Yönlendiriliyorsun…",
    toggleToSignUp: "Hesabın yok mu? Kayıt ol",
    toggleToSignIn: "Zaten hesabın var mı? Giriş yap",
    backToHome: "Ana Sayfaya Dön",
    emailRequired: "E-posta adresi gerekli",
    passwordRequired: "Şifre gerekli",
    passwordMinLength: "Şifre en az 6 karakter olmalı",
    invalidEmail: "Geçerli bir e-posta adresi girin",
    weakPassword: "Şifre çok zayıf. En az 6 karakter olmalı",
    emailInUse: "Bu e-posta adresi zaten kullanılıyor",
    userNotFound: "Bu e-posta adresi ile kayıtlı kullanıcı bulunamadı",
    wrongPassword: "Şifre yanlış",
  },
  nav: {
    dashboard: "Vakalar",
    profile: "Profil",
    leaderboard: "Liderlik Tablosu",
    logout: "Çıkış yap",
    login: "Giriş",
  },
  dashboard: {
    title: "Vakalar",
    placeholder:
      "Burası oyun akışı için başlangıç noktası olacak. (İskelet sayfa)",
  },
  cases: {
    list: {
      title: "Vakalar",
      startButton: "Vakayı Başlat",
    },
    briefing: "Durum Raporu",
    clues: "Kanıtlar",
    notFound: "Vaka bulunamadı",
    case001: {
      title: "Müze Soygunu",
      briefing:
        "Dün gece saat 23:00'te müze güvenlik sisteminden alarm çaldı. Güvenlik görevlileri olay yerine vardığında, önemli bir tablo kayıptı. Olay yerinde bazı ipuçları bulundu.",
      clues: {
        clue1: "Tablo Depo-Arşiv'den çalınmadı.",
        clue2: "Cam Kesici'yi kullanan kişi Aylin değildi.",
        clue3: "Ziyaretçi kayıtlarına göre Cem, o gece Restorasyon Atölyesi'ne hiç girmedi.",
        clue4: "Olay yerindeki kesim izi, kullanılan aletin doğrudan cam kesimi olduğunu gösteriyor.",
        clue5: "Kart Kopyalayıcı cihazı, Baran'ın imzasıyla kayıtlıydı.",
      },
    },
    case002: {
      title: "Otel Cinayeti",
      briefing:
        "Lüks otelin 5. katında bir oda hizmetçisi ceset buldu. Kurban, odasında ölü bulundu ve birkaç değerli eşya eksikti. Kapı zorla açılmıştı. Kurbanın cep telefonu kayıp ve henüz bulunamadı.",
      clues: {
        clue1: "Deniz sadece hafif bir silah taşıyabildi.",
        clue2: "Zehirli içecek servis koridoru üzerinden taşındı.",
        clue3: "Mert merdiven boşluğunu kullanmak zorundaydı.",
        clue4: "Merdiven boşluğunu kullanan kişi ağır bir nesne taşıyordu.",
        clue5: "Kurbanın boynundaki kesik izleri, cinayetin kesici bir silahla işlendiğini gösteriyor.",
      },
    },
  },
  suspects: {
    suspect001: "Aylin Kara",
    suspect002: "Baran Yıldız",
    suspect003: "Cem Aras",
    suspect004: "Ayşe Öztürk",
    suspect005: "Can Arslan",
    suspect006: "Deniz Yıldız",
    suspect007: "Deniz Aksoy",
    suspect008: "Mert Kıraç",
    suspect009: "Selin Vural",
    icon001: "👤",
    icon002: "👩",
    icon003: "👨",
    icon004: "👩",
    icon005: "👨",
    icon006: "👤",
    icon007: "👩",
    icon008: "👨",
    icon009: "👩",
    bio001: "Baş Restoratör. Müzede 8 yıldır çalışıyor. Tablo restorasyonu konusunda uzman. Çalışma saatleri 09:00-17:00.",
    bio002: "Gece Güvenlik Şefi. 3 yıldır müzede görevli. Tüm güvenlik sistemlerinden sorumlu. Gece 18:00-06:00 arası görevde.",
    bio003: "Bağışçı ve koleksiyoncu. Müzenin önemli destekçilerinden biri. Nadir tabloların sahibi. Genellikle hafta sonları müzeyi ziyaret eder.",
    bio007: "Oda Hizmetleri Sorumlusu. Bilek sakatlığı var, sadece hafif silahları taşıyabilir.",
    bio008: "Güvenlik Görevlisi. Güçlü, merdiven boşluğunu kullanmak zorunda.",
    bio009: "Etkinlik Koordinatörü. VIP koordinatörü, içecek taşır.",
  },
  locations: {
    location001: "Ana Galeri",
    location002: "Restorasyon Atölyesi",
    location003: "Depo-Arşiv",
    location004: "Oda 501",
    location005: "Oda 502",
    location006: "Oda 503",
    location007: "Kurbanın Odası (504)",
    location008: "Servis Koridoru (Personel Geçişi)",
    location009: "Merdiven Boşluğu (Acil Çıkış)",
    icon001: "🖼️",
    icon002: "🛠️",
    icon003: "📦",
    icon004: "🛏️",
    icon005: "🛏️",
    icon006: "🛏️",
    icon007: "🛏️",
    icon008: "🚪",
    icon009: "🪜",
    desc001: "Müzenin ana sergi alanı. Değerli tabloların sergilendiği bölüm. Güvenlik kameraları ve alarm sistemleri mevcut.",
    desc002: "Tablo ve eserlerin onarım ve restorasyon işlemlerinin yapıldığı atölye. Sadece yetkili personel girebilir.",
    desc003: "Eserlerin depolandığı arşiv bölümü. İklim kontrollü ortam. Sıkı güvenlik protokolleri var.",
    desc007: "Misafir Odası. Kurbanın bulunduğu yer.",
    desc008: "Servis Koridoru. Personel geçiş alanı.",
    desc009: "Merdiven Boşluğu. Acil çıkış alanı.",
  },
  weapons: {
    weapon001: "Cam Kesici",
    weapon002: "Manyetik Kart Kopyalayıcı",
    weapon003: "Sessiz Matkap",
    weapon004: "Yastık",
    weapon005: "Bardak",
    weapon006: "Halat",
    weapon007: "Kırık Şişe",
    weapon008: "Metal Levye",
    weapon009: "Zehirli İçecek",
    icon001: "🔪",
    icon002: "💳",
    icon003: "🔩",
    icon004: "🛏️",
    icon005: "🥛",
    icon006: "🪢",
    icon007: "🍷",
    icon008: "🔧",
    icon009: "🚬",
    desc001: "Özel cam kesme aleti. Vitrin camlarını sessizce ve temiz bir şekilde kesmek için kullanılır.",
    desc002: "Güvenlik kartlarını kopyalamak için kullanılan cihaz. Manyetik şerit bilgilerini okur ve kopyalar.",
    desc003: "Düşük sesli elektrikli matkap. Duvar delmek veya kilit mekanizmalarını aşmak için kullanılabilir.",
    desc007: "Kırık Şişe. Kesici silah, orta ağırlıkta.",
    desc008: "Metal Levye. Kesici değil, ağır silah.",
    desc009: "Zehirli İçecek. Kesici değil, hafif silah.",
  },
  grid: {
    title: "Dedektif Not Defteri",
    suspects: "KİM",
    locations: "NEREDE",
    weapons: "NEYLE",
    finalDeduction: "Son Çıkarım",
    submitReport: "Raporu Gönder",
    submitDisabledHint: "Tüm alanları doldurun",
  },
  result: {
    success: {
      title: "Tebrikler!",
      message: "Vakayı başarıyla çözdünüz!",
    },
    failure: {
      title: "Yanlış Çözüm",
      message: "Seçimleriniz doğru değil. Kanıtları tekrar gözden geçirin.",
    },
    stats: {
      duration: "Süre",
      attempts: "Deneme Sayısı",
    },
    actions: {
      retry: "Tekrar Dene",
      dashboard: "Dashboard'a Dön",
      nextCase: "Sonraki Vaka",
    },
    validation: {
      wrongSuspect: "Yanlış şüpheli seçtiniz.",
      wrongLocation: "Yanlış konum seçtiniz.",
      wrongWeapon: "Yanlış silah seçtiniz.",
    },
  },
  difficulty: {
    label: "Zorluk:",
    easy: "Kolay",
    medium: "Orta",
    hard: "Zor",
  },
  profile: {
    title: "Profil",
    stats: "İstatistikler",
    totalScore: "Toplam Skor",
    solvedCases: "Çözülen Vakalar",
    averageTime: "Ortalama Süre",
    totalAttempts: "Toplam Deneme",
    caseResults: "Oyun Geçmişi",
    noResults: "Henüz tamamlanan vaka yok.",
    case: "Vaka",
    score: "Skor",
    time: "Süre",
    attempts: "Deneme",
    completedAt: "Tamamlanma",
    filterAll: "Tüm Vakalar",
    filterWins: "Başarılı Vakalar",
    filterLosses: "Başarısız Vakalar",
    clearHistory: "Geçmişi Temizle",
    clearHistoryConfirm: "Tüm oyun geçmişiniz kalıcı olarak silinecek. Emin misiniz?",
    clearHistorySuccess: "Oyun geçmişi başarıyla temizlendi.",
    clearHistoryError: "Geçmiş temizlenirken bir hata oluştu.",
    editProfile: "Profili Düzenle",
    saveProfile: "Kaydet",
    cancelEdit: "İptal",
    usernameLabel: "Dedektif Kullanıcı Adı",
    usernamePlaceholder: "Kullanıcı adınızı girin",
    usernameRequired: "Kullanıcı adı gerekli",
    usernameMinLength: "Kullanıcı adı en az 3 karakter olmalı",
    usernameMaxLength: "Kullanıcı adı en fazla 20 karakter olmalı",
    usernameInvalid: "Kullanıcı adı sadece harf, rakam ve alt çizgi içerebilir",
    avatarLabel: "Avatar Seçimi",
  },
  profileSetup: {
    title: "Profil Oluştur",
    subtitle: "Oyuna başlamak için profilinizi oluşturun",
    usernameLabel: "Dedektif Kullanıcı Adı",
    usernamePlaceholder: "Kullanıcı adınızı girin",
    usernameRequired: "Kullanıcı adı gerekli",
    usernameMinLength: "Kullanıcı adı en az 3 karakter olmalı",
    usernameMaxLength: "Kullanıcı adı en fazla 20 karakter olmalı",
    usernameInvalid: "Kullanıcı adı sadece harf, rakam ve alt çizgi içerebilir",
    avatarLabel: "Avatar Seçimi",
    saveButton: "Profili Oluştur",
    saving: "Oluşturuluyor...",
  },
  leaderboard: {
    title: "Liderlik Tablosu",
    global: "Genel Sıralama",
    caseSpecific: "Vakaya Özel Sıralama",
    selectCase: "Vaka Seç",
    rank: "Sıra",
    player: "Oyuncu",
    score: "Skor",
    cases: "Vakalar",
    time: "Süre",
    attempts: "Deneme",
    loading: "Yükleniyor...",
    noEntries: "Henüz sıralama yok.",
  },
  errors: {
    unknown: "Bir şeyler ters gitti.",
    network: "Ağ bağlantısı hatası. Lütfen tekrar dene.",
    authPopupClosed: "Giriş penceresi kapatıldı.",
    authFailed: "Giriş başarısız. Lütfen tekrar dene.",
    configMissing:
      "Uygulama yapılandırması eksik. Lütfen ortam değişkenlerini kontrol et.",
  },
  a11y: {
    appLogoAlt: "NoirNote logosu",
  },
} as const;

export type TextsTR = typeof textsTR;

